# Generated by Django 2.2.16 on 2022-11-02 08:53

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20221031_1836'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='users_cannot_follow_themselves',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('following')), name='users_cannot_follow_themselves'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_name_following'),
        ),
    ]
